// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEE6GDo17SDGLoKfZcO_kHksEjhfmnPmM',
    appId: '1:985090241978:web:df9709ddc5d0ffbfc95983',
    messagingSenderId: '985090241978',
    projectId: 'udec-77c9c',
    authDomain: 'udec-77c9c.firebaseapp.com',
    storageBucket: 'udec-77c9c.appspot.com',
    measurementId: 'G-357V3NDME0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABlTuDTLMpP72uuqCCdq-iASerkTxCG6I',
    appId: '1:985090241978:android:e45311fc55bb1fa7c95983',
    messagingSenderId: '985090241978',
    projectId: 'udec-77c9c',
    storageBucket: 'udec-77c9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj_1BSva_-MD6q39lXDXC0Hj9LkxcGP0M',
    appId: '1:985090241978:ios:0da210003761dd2dc95983',
    messagingSenderId: '985090241978',
    projectId: 'udec-77c9c',
    storageBucket: 'udec-77c9c.appspot.com',
    iosClientId: '985090241978-rllkl7ob8fbd76mb7ogumhd43ficnbt3.apps.googleusercontent.com',
    iosBundleId: 'co.edu.ucundinamarca.primero',
  );
}
